version: '1.0.{build}'
image: Visual Studio 2017
# https://dotnetcore.gaprogman.com/2017/06/08/continuous-integration-and-appveyor/
branches:
  only:
  - master

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - ps: | 
      cd e2e-helpers
      npm install

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Start LDAP test server
  - ps: |
      cd e2e-helpers
      $MyProcess = Start-Process npm -ArgumentList 'run serve'
  # Display minimal restore text
  - cmd: dotnet restore ./Linq2Ldap.sln --verbosity m

build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./Linq2Ldap.sln

test_script:
  - ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./ Linq2Ldap.Tests/Linq2Ldap.Tests.csproj
  - ps: dotnet test Linq2Ldap.IntegrationTest

after_test:
  - ps: Stop-Process -Id $MyProcess.Id
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "Linq2Ldap.Tests/coverage.opencover.xml"